# Generated by Django 4.1.5 on 2023-02-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('expected_result', models.TextField()),
                ('content_file', models.FileField(blank=True, null=True, upload_to='homework_files')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advancement_level', models.CharField(choices=[('Podstawowy', 'Basic'), ('Średnio-zaawansowany', 'Semi Advanced'), ('Zaawansowany', 'Advanced')], max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_office.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringOfficeSubjectVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conducting_classes_mode', models.CharField(choices=[('Indywidualne', 'Solo'), ('Para', 'Pair'), ('Grupa', 'Group')], default='Indywidualne', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subject_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_office.subjectvariant')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringOfficeFinancialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_bill', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rent_bill', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gas_bill', models.DecimalField(decimal_places=2, max_digits=9)),
                ('water_bill', models.DecimalField(decimal_places=2, max_digits=9)),
                ('internet_bill', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_maintenance_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_employee_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('generate_date', models.DateField(auto_now_add=True)),
                ('tutoring_office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tutoring_office.tutoringoffice')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherQualityOfServiceAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.CharField(choices=[('&starf;', 'Bad'), ('&starf;&starf;', 'Decent'), ('&starf;&starf;&starf;', 'Ok'), ('&starf;&starf;&starf;&starf;', 'Great'), ('&starf;&starf;&starf;&starf;&starf;', 'Awesome')], max_length=50)),
                ('generate_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedbacks_for_teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='quality_of_service_assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_comment', models.TextField(blank=True, default='')),
                ('student_answer', models.TextField(blank=True, default='')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Fail'), (2, 'Passing'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True)),
                ('due_date', models.DateTimeField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tutoring_office.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_homeworks', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_homeworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('generate_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDevelopmentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.CharField(choices=[('&starf;', 'Bad'), ('&starf;&starf;', 'Decent'), ('&starf;&starf;&starf;', 'Ok'), ('&starf;&starf;&starf;&starf;', 'Great'), ('&starf;&starf;&starf;&starf;&starf;', 'Awesome')], max_length=50)),
                ('generate_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='development_assessments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedbacks_for_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='subject_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tutoring_office.subjectvariant'),
        ),
        migrations.CreateModel(
            name='EmployeeFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('generate_date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_url', models.URLField()),
                ('date', models.DateTimeField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tutoring_office.classgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('tutoring_office_subject_variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tutoring_office.tutoringofficesubjectvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tutoring_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring_office.tutoringoffice')),
            ],
        ),
    ]
